### ISSUE TITLE
getSignaturesForAddress Returns Empty Array ([]) Despite Running Faithful RPC Server

### ISSUE THREAD

**Issue by AshishG2** [rpcpool/yellowstone-faithful#226]
When running the `faithful-cli` RPC server, most RPC methods function correctly. However, the `getSignaturesForAddress` method always returns an empty array (`[]`), even when querying addresses that have known transaction history. This issue persists despite using the latest available `gsfa` index.

### Steps to Reproduce

1. Clone the repository and build the CLI binaries:
   ```sh
   git clone https://github.com/rpcpool/yellowstone-faithful.git
   cd yellowstone-faithful
   make jsonParsed-linux  # Or use the appropriate build command
   ```

2. Start the Faithful RPC Server:
   ```sh
   faithful-cli rpc --listen=:8888 epoch-701.yml
   ```

3. Query `getSignaturesForAddress`:
   ```sh
   curl -X POST http://localhost:8888 -H "Content-Type: application/json" -d '{
     "jsonrpc": "2.0",
     "id": 1,
     "method": "getSignaturesForAddress",
     "params": ["<wallet_address>"]
   }'
   ```

4. Observe the response:
   - **Expected:** A list of transaction signatures for the given address.
   - **Actual:** An empty array (`[]`), even when transactions exist.

### GSFA Index Used
I am using the following `gsfa` index file:
📌 **[epoch-701-gsfa.index.tar.zstd](https://files.old-faithful.net/701/epoch-701-gsfa.index.tar.zstd)**

### Expected vs. Actual Behavior

| Query Method                     | Expected Response (Mainnet RPC) | Actual Response (Faithful RPC) |
|-----------------------------------|--------------------------------|--------------------------------|
| `getSignaturesForAddress`         | List of transaction signatures | `[]` (empty array) |

### Additional Details
- Issue persists even with the latest `gsfa` index.
- Other RPC methods appear to be working correctly.
- No additional error messages appear in the Faithful server logs.

Would appreciate any guidance or troubleshooting steps on resolving this issue.

**Comment by Lusitaniae** [comment]
Possibly you need to find accounts that have signatures in that specific epoch?

If I check at the last block of epoch 701: https://explorer.solana.com/block/303263999
Take one of the txs: https://explorer.solana.com/tx/rhDpGxayZAfQa18SLZX1AsTVzzsptHEJaFuBB3NcfXqXFnAakTMeXAYzUgMamuskRojg3jQQi97LqyxMFGSv4uU

```
faithful-cli version | grep rev
  vcs.revision: aedbfe047debc3199da771db06417ae0026e8643
```


I can see lots of results

```
curl localhost:8897 -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 9999,
    "method": "getSignaturesForAddress",
    "params": [ "FetTyW8xAYfd33x4GMHoE7hTuEdWLj1fNnhJuyVMUGGa" ]
  }
' -s | jq -r .result[].signature
62kkYb2FbWpbKD8L7Jnst1oZdbgSMs1up5E8AZCvD8EyUsR5EhCRHZoFZQo3JAfHrKgVd7V1kUBc83YzZT8id5wk
orAqu4GgyGyu8zMDCaHCb4usVb4xU9DDyStV3d94thQF5WQ7g1ZBarzPQYJ9j4yr7QxQUhNvA9wK8A7V5APt8PS
3gCJcFxabS3NAATzFzzRSKtw87Nu49tNeivcokZEJfzcJqcPxBpkuGSjFYAMyc2oPBvravjyCPpGhv8n9fqXKrNx
...
```


```
/usr/local/bin/faithful-cli -v=2 rpc --listen :8888 --grpc-listen :8889 -p -vv --watch /tank/storage/701.yml
I0213 09:09:04.779112 3927614 cmd-rpc.go:128] Found 1 config files:
I0213 09:09:04.795620 3927614 cmd-rpc.go:154] Loaded 1 epoch configs
I0213 09:09:04.795627 3927614 cmd-rpc.go:155] Initializing epochs async...
I0213 09:09:04.795641 3927614 cmd-rpc.go:233] Found 1 directories; will start watching them for changes ...
I0213 09:09:04.795732 3927614 multiepoch.go:234] RPC server listening on :8888
I0213 09:09:04.795944 3927614 storage.go:64] opening CAR file from "http://168.119.199.68/701/epoch-701.car" as HTTP remote file
I0213 09:09:04.804869 3927614 cmd-rpc.go:221] Initialized 1/1 epochs in 9.22724ms

```


```
cat /tank/hetzner-storage/701.yml
version: 1 
epoch: 701
data:
  car:
    uri: http://168.119.199.68/701/epoch-701.car
  filecoin:
    enable: false
indexes:
  cid_to_offset_and_size:
    uri: /tank/701/epoch-701-bafyreie6lxslznaemfnpkss3wapzm3aje62tbcdiwnilhulurjlsiucqbq-mainnet-cid-to-offset-and-size.index
  slot_to_cid:
    uri: /tank/701/epoch-701-bafyreie6lxslznaemfnpkss3wapzm3aje62tbcdiwnilhulurjlsiucqbq-mainnet-slot-to-cid.index
  slot_to_blocktime:
    uri: /tank/701/epoch-701-bafyreie6lxslznaemfnpkss3wapzm3aje62tbcdiwnilhulurjlsiucqbq-mainnet-slot-to-blocktime.index
  sig_to_cid:
    uri:  /tank/701/epoch-701-bafyreie6lxslznaemfnpkss3wapzm3aje62tbcdiwnilhulurjlsiucqbq-mainnet-sig-to-cid.index
  sig_exists:
    uri: /tank/701/epoch-701-bafyreie6lxslznaemfnpkss3wapzm3aje62tbcdiwnilhulurjlsiucqbq-mainnet-sig-exists.index
  gsfa:
    uri: /tank/701/epoch-701-bafyreie6lxslznaemfnpkss3wapzm3aje62tbcdiwnilhulurjlsiucqbq-mainnet-gsfa.indexdir
```
