### ISSUE TITLE
Support split epochs

### ISSUE THREAD

**Issue by linuskendall** [rpcpool/yellowstone-faithful#54]
```
data:
  car: 
      - uri: split1
        length: 1231123
      - uri: split2
        length: 1231122
  filecoin:
    enable: false
epoch: 485
indexes:
  cid_to_offset:
    uri: /faithful/485/epoch-485.car.bafyreicq2owurw55aye55e6ckzf6mvjlme6ur3qu3ahe6r7xivtn4j5lsq.cid-to-offset.index
  sig_to_cid:
    uri: /faithful/485/epoch-485.car.bafyreicq2owurw55aye55e6ckzf6mvjlme6ur3qu3ahe6r7xivtn4j5lsq.sig-to-cid.index
  slot_to_cid:
    uri: /faithful/485/epoch-485.car.bafyreicq2owurw55aye55e6ckzf6mvjlme6ur3qu3ahe6r7xivtn4j5lsq.slot-to-cid.index
  sig_exists:
    uri: /faithful/485/epoch-485.car.bafyreicq2owurw55aye55e6ckzf6mvjlme6ur3qu3ahe6r7xivtn4j5lsq.sig-exists.index
```
